header_literal = '''
// generated by scripts/HeaderLiteral.py\n
#include "Operator.hpp"
#include "Basic.hpp"
#include "Value.hpp"
#include "Decode.hpp"
#include "Processor.hpp"
#include "RawDatumOperand.hpp"

#include "arith.h"

#include <cassert>
#include <ostream>
'''
