#!/bin/bash

FLASH_TOOL="/root/arty_tools/xc3sprog/xc3sprog_ole2mail/build/xc3sprog"
ARTY_RUN_PATH="/root/arty_tools/metal-run/arty-run"
BITSTREAM_PATH="/root/arty_tools/bitstream"
VERSION="1908"
BINARY_PATH="/root/arty_tools/hello"
COREIP_LIST="s76 e20 e31"
FIND_USB="/root/arty_tools/find.sh"

GDB_PATH="/root/arty_tools/riscv-toolchain/bin/riscv64-unknown-elf-gdb"
OPENOCD_PATH="/usr/local/bin/openocd"
OPENOCD_CONFIG="/root/arty_tools/openocd.cfg"

bitstream=$1
executable=$2

timeout=$3


if [ "$#" != "3" ];then
    echo -e "\n$0 [bitstream] [executable] [timeout]\n"
    echo -e "    bitstream : .bit file for arty"
    echo -e "    executable: ELF file generated by freedom-e-sdk"
    echo -e "    timeout: timeout for executing executable in second"
    exit -1
fi

# prepare ttyUSB
OUTPUT_TTY=`bash $FIND_USB 2>&1 |grep "\/dev\/ttyUSB.*Digilent.*[0-9A-Z]$" |cut -d- -f1 |sed "s/ //g"`
if [ ! -e $OUTPUT_TTY ];then
    echo "Output TTY: ${OUTPUT_TTY} doesn't exist"
    exit -1
fi



if [ ! -e $executable ];then
	echo "$executable not exist !"
	exit -1
fi
executable=`readlink -f $executable`

if [ ! -e $bitstream ];then 
	echo "$bitstream not exist !"
	exit -1
fi
bitstream=`readlink -f $bitstream`

echo -e "\n==== found $OUTPUT_TTY as I/O serial port !  ==== "

#burn
echo -e "\n==== start to flash bitstream `basename $bitstream` on arty  ==== "
$FLASH_TOOL -c nexys4 -v $bitstream
if [ "$?" != "0" ];then
	echo "flash error for $bitstream"
	exit -1
fi

echo -e "\n==== flash success ! try to run program `basename $executable` ==== "
#run
$ARTY_RUN_PATH --gdb $GDB_PATH --openocd $OPENOCD_PATH --openocd-config $OPENOCD_CONFIG --tty $OUTPUT_TTY --executable $executable --timeout $timeout

exit $?

