#! /usr/bin/env python3

import argparse
import sys
from collections import defaultdict

def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", help="Output file", required=True)
    parser.add_argument("inputs", nargs='+', help="*.qhist files.")

    opt = parser.parse_args(args)

    hist = defaultdict(int)

    total_count = 0

    for filename in opt.inputs:
        with open(filename, "r") as f:
            first_line = True
            for line in f:
                line = line.strip()
                if first_line:
                    # Check first line is "pc,dyn_insn_count"
                    if not line.startswith("pc,dyn_insn_count"):
                        raise Exception("Unexpected format in %s" % filename)
                    first_line = False
                    continue
                if line.startswith("pc,dyn_insn_count"):
                    continue
                pc, inst_count = line.split(",")
                pc = int(pc, 16)
                inst_count = int(inst_count)
                hist[pc] += inst_count
                total_count += inst_count

    with open(opt.o, "w") as f:
        f.write("pc,dyn_insn_count,%s\n"%total_count)
        for pc, inst_count in hist.items():
            f.write("0x%x,%d\n" % (pc, inst_count))

main(sys.argv[1:])
