#! /usr/bin/env python3

import argparse
import sys
from collections import defaultdict

def openfile(filename):
    if filename == '-':
        return sys.stdout
    else:
        return open(filename, "w")

def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", help="Output file", required=True)
    parser.add_argument("inputs", nargs='+', help="*.qhist files.")

    opt = parser.parse_args(args)

    hist = defaultdict(int)

    total_inst_count = 0

    for filename in opt.inputs:
        with open(filename) as f:
            first_line = True
            for line in f:
                line = line.strip()
                if first_line:
                    # Check first line is "pc,dyn_insn_count"
                    if not line.startswith("pc,dyn_insn_count"):
                        raise Exception("Unexpected format in %s" % filename)
                    if len(line.split(",")) == 3:
                        total_inst_count = int(line.split(",")[2])
                        break
                    first_line = False
                    continue
                pc, inst_count = line.split(",")
                pc = int(pc, 16)
                inst_count = int(inst_count)
                total_inst_count += inst_count

    with openfile(opt.o) as f:
        f.write("%d\n" % (total_inst_count))

main(sys.argv[1:])
