name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 16
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: '[NFC] Auto-commit clang-format from github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
